#using message catalogs
#randall hobart started on 8-20-2023

msgcat::mcflmset {
	"title"	{PrePressActions}
	"m_File"	{File}
	"m_clearLog"	{Clear Logging Information}
	"m_WrapLines"	{Wrap Lines}
	"m_UnWrapLines"	{UnWrap Lines}
	"m_quit"	{Exit Ctl-x}
	"ConvertFile" {ConvertFile}
	"m_showDpiDialog" {Set DPI preference...}
	"m_openPDFtoTiff" {Open PDF,EPS,PS and Separate to cmyk + spot tiffs...}
	"m_openImagetoMono" {Open Image and Create mono Bitmap create tiff...}
	"m_openTIFFandInvert" {Open Image and Invert -negate create tiff...}
	"m_showSwellDialog" {Set Swell size...}
	"m_openTIFFandSwell" {Open Image and Swell Edges create tiff...}
	"m_openImageFlipHorizontal" {Open Image and Flip Horizontal to tiff...}
	"m_openImageFlipVertical" {Open Image and Flip Vertical to tiff...}
	"m_showBatchDialog" {Batch Conversion Settings...}
	"m_openDirBatchScaleImgs" {Open Directory and Batch Scale Imgs...}
	"m_openImageCreatePDF" {Open Image and Create PDF...}
	"m_openPSCreatePDF" {Open PS and Create PDF...}
	"m_openPDFCreatePS" {Open PDF and Create PS...}
	"m_openPDFCreateGrayscalePDF" {Open PDF or PS and Create Grayscale PDF...}
	"m_Identify" {Inspect}
	"m_openImagePdfEpsInfoAll" {Identify-Open Image/PDF/EPS -ALL)...}
	"m_openImagePdfEpsInfoSummary" {Identify-Open Image/PDF/EPS summary...}
	"m_openPdfPsPdfinfo" {pdfinfo-Open PDF show Media Sizes...}
	"m_Vector" {Vector}
	"m_openBitmapPBMCreatePS" {Open .pbm file -> Create Vector file...}
	"m_openImageCreatePBM" {Open Image and Create .pbm file...}
	"m_Inkcoverage" {InkCoverage}
	"m_measureCMYK" {Measure coverage cmyk...}
	"m_measureCMYKspot" {Measure coverage cmyk+spot...}
	"m_printerProfilesWin" {Add/Edit or Select Printer Profiles...}
	"m_Help" {Help}
	"m_help" {PrePress Help...}
}
